# dbPilotageKey = "Perf-RSE-SIFCA"
dbPilotageKey = "Perf-ENERGIE"

userCollection = "User"
accesPilotageCollection = ""
indicateurCollection = ""
entityCollection = ""
dataEntityCollection = ""
monitoringCollection = ""
performanceCollection = ""
